// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`syncWorker login should catch errors and log them 1`] = `
Array [
  "
Error: post failed
    at Object.spyOn.and.callFake (/Users/daneryl/workspace/uwazi/app/api/sync/specs/syncWorker.spec.js:153:64)
    at Object.SpyStrategy.exec (/Users/daneryl/workspace/uwazi/node_modules/jest-jasmine2/build/jasmine/spy_strategy.js:53:17)
    at Object.spy [as post] (/Users/daneryl/workspace/uwazi/node_modules/jest-jasmine2/build/jasmine/create_spy.js:67:42)
    at Object.post [as login] (/Users/daneryl/workspace/uwazi/app/api/sync/syncWorker.js:77:38)
    at Object.login (/Users/daneryl/workspace/uwazi/app/api/sync/specs/syncWorker.spec.js:154:24)
    at Object.asyncJestTest (/Users/daneryl/workspace/uwazi/node_modules/jest-jasmine2/build/jasmine_async.js:108:37)
    at resolve (/Users/daneryl/workspace/uwazi/node_modules/jest-jasmine2/build/queue_runner.js:56:12)
    at new Promise (<anonymous>)
    at mapper (/Users/daneryl/workspace/uwazi/node_modules/jest-jasmine2/build/queue_runner.js:43:19)
    at promise.then (/Users/daneryl/workspace/uwazi/node_modules/jest-jasmine2/build/queue_runner.js:87:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)",
]
`;
